-- MySQL Script generated by MySQL Workbench
-- Sat Jul 26 22:12:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simpsons_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `simpsons_api` ;

-- -----------------------------------------------------
-- Schema simpsons_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simpsons_api` DEFAULT CHARACTER SET utf8 ;
USE `simpsons_api` ;

-- -----------------------------------------------------
-- Table `simpsons_api`.`personajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simpsons_api`.`personajes` ;

CREATE TABLE IF NOT EXISTS `simpsons_api`.`personajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpsons_api`.`capitulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simpsons_api`.`capitulos` ;

CREATE TABLE IF NOT EXISTS `simpsons_api`.`capitulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `numero_episodio` INT NULL,
  `temporada` INT NULL,
  `fecha_emision` DATE NULL,
  `sinopsis` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpsons_api`.`frases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simpsons_api`.`frases` ; -- Esta línea es opcional si siempre haces DROP SCHEMA

CREATE TABLE IF NOT EXISTS `simpsons_api`.`frases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(255) NOT NULL,
  `marca_tiempo` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `personaje_id` INT NOT NULL,  -- Asegúrate de que esta columna exista
  `capitulo_id` INT NULL,       -- Asegúrate de que esta columna exista y el tipo de dato sea correcto (NULL si permites frases sin capítulo)
  PRIMARY KEY (`id`),
  INDEX `fk_frases_personaje_idx` (`personaje_id` ASC) VISIBLE,
  INDEX `fk_frases_capitulo_idx` (`capitulo_id` ASC) VISIBLE,
  CONSTRAINT `fk_frases_personaje`
    FOREIGN KEY (`personaje_id`)
    REFERENCES `simpsons_api`.`personajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frases_capitulo`
    FOREIGN KEY (`capitulo_id`)
    REFERENCES `simpsons_api`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpsons_api`.`personajes_has_capitulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simpsons_api`.`personajes_has_capitulos` ;

CREATE TABLE IF NOT EXISTS `simpsons_api`.`personajes_has_capitulos` (
  `personajes_id` INT NOT NULL,
  `capitulos_id` INT NOT NULL,
  PRIMARY KEY (`personajes_id`, `capitulos_id`),
  INDEX `fk_personajes_has_capitulos_capitulos1_idx` (`capitulos_id` ASC) VISIBLE,
  INDEX `fk_personajes_has_capitulos_personajes1_idx` (`personajes_id` ASC) VISIBLE,
  CONSTRAINT `fk_personajes_has_capitulos_personajes1`
    FOREIGN KEY (`personajes_id`)
    REFERENCES `simpsons_api`.`personajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personajes_has_capitulos_capitulos1`
    FOREIGN KEY (`capitulos_id`)
    REFERENCES `simpsons_api`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- INSERT INTO personajes
INSERT INTO `simpsons_api`.`personajes` (`id`, `nombre`, `apellido`, `ocupacion`, `descripcion`) VALUES
(1, 'Homer', 'Simpson', 'Nuclear Safety Inspector', 'Homer es el padre de la familia Simpson, conocido por su torpeza y amor por la cerveza.'),
(2, 'Marge', 'Simpson', 'Ama de casa', 'Marge es la madre de la familia Simpson, reconocida por su cabello azul y su paciencia.'),
(3, 'Bart', 'Simpson', NULL, 'Bart es el hijo travieso de Homer y Marge, famoso por sus bromas y travesuras.'),
(4, 'Lisa', 'Simpson', NULL, 'Lisa es la hija inteligente y preocupada por el medio ambiente de Homer y Marge.'),
(5, 'Maggie', NULL, NULL, 'La bebé de la familia Simpson, conocida por su chupete.'),
(6, 'Mr. Burns', 'Burns', 'Dueño de la Central Nuclear de Springfield', 'El jefe de Homer, anciano y malvado.'); -- Añadido Mr. Burns para las frases

-- INSERT INTO capitulos
INSERT INTO `simpsons_api`.`capitulos` (`titulo`, `numero_episodio`, `temporada`, `fecha_emision`, `sinopsis`) VALUES
('Bart el Genio', 2, 1, '1990-01-14', 'Bart hace trampa en una prueba de CI y es transferido a una escuela para superdotados.'),
('El Cuarteto de Homer', 3, 5, '1993-09-30', 'Homer forma un cuarteto de barbería que alcanza la fama.'),
('Cabo de Miedo', 2, 5, '1993-10-07', 'Sideshow Bob es liberado de prisión y persigue a Bart.');

-- INSERT INTO frases
INSERT INTO `simpsons_api`.`frases` (`texto`, `personaje_id`, `capitulo_id`, `marca_tiempo`, `descripcion`) VALUES
('¡D''oh!', (SELECT id FROM personajes WHERE nombre = 'Homer'), (SELECT id FROM capitulos WHERE titulo = 'El Cuarteto de Homer'), '00:30', 'La clásica exclamación de Homer.'),
('Excelente...', (SELECT id FROM personajes WHERE nombre = 'Mr. Burns'), NULL, NULL, 'La frase del Sr. Burns.'),
('¡Ay, caramba!', (SELECT id FROM personajes WHERE nombre = 'Bart'), (SELECT id FROM capitulos WHERE titulo = 'Bart el Genio'), '01:15', 'El latiguillo de Bart.'),
('Mmm... rosquillas.', (SELECT id FROM personajes WHERE nombre = 'Homer'), NULL, NULL, 'Una de las frases más icónicas de Homer sobre su pasión por las rosquillas.');

-- INSERT INTO personajes_has_capitulos (si quieres poblar esta tabla también)
INSERT INTO `simpsons_api`.`personajes_has_capitulos` (`personajes_id`, `capitulos_id`) VALUES
((SELECT id FROM personajes WHERE nombre = 'Homer'), (SELECT id FROM capitulos WHERE titulo = 'El Cuarteto de Homer')),
((SELECT id FROM personajes WHERE nombre = 'Bart'), (SELECT id FROM capitulos WHERE titulo = 'Bart el Genio')),
((SELECT id FROM personajes WHERE nombre = 'Bart'), (SELECT id FROM capitulos WHERE titulo = 'Cabo de Miedo')),
((SELECT id FROM personajes WHERE nombre = 'Lisa'), (SELECT id FROM capitulos WHERE titulo = 'Cabo de Miedo'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
